### ISSUE TITLE
Spring DevTools Labels not loads IllegalStateException

### ISSUE THREAD

**Issue by sesong11** [zkoss/zkspringboot#11]
When DevTools reload Labels no longer accessible with exception

```
2019-03-27 14:01:37.254 ERROR 6628 --- [nio-8080-exec-6] org.zkoss.mesg.Messages                  : Message code not found: 27112012 not in en_US:[org.zkoss.zul.mesg.MZul, /metainfo/mesg/msgzul]
2019-03-27 14:01:37.254  INFO 6628 --- [nio-8080-exec-6] o.z.util.resource.impl.LabelLoaderImpl   : Loading labels for en_US
2019-03-27 14:01:37.256 ERROR 6628 --- [nio-8080-exec-6] org.zkoss.mesg.Messages                  : 

java.lang.IllegalStateException: The resources may not be accessed if they are not currently started
	at org.apache.catalina.webresources.StandardRoot.validate(StandardRoot.java:246) ~[tomcat-embed-core-9.0.14.jar:9.0.14]
	at org.apache.catalina.webresources.StandardRoot.getResource(StandardRoot.java:212) ~[tomcat-embed-core-9.0.14.jar:9.0.14]
	at org.apache.catalina.webresources.StandardRoot.getResource(StandardRoot.java:206) ~[tomcat-embed-core-9.0.14.jar:9.0.14]
	at org.apache.catalina.core.ApplicationContext.getResource(ApplicationContext.java:539) ~[tomcat-embed-core-9.0.14.jar:9.0.14]
	at org.apache.catalina.core.ApplicationContextFacade.getResource(ApplicationContextFacade.java:200) ~[tomcat-embed-core-9.0.14.jar:9.0.14]
	at org.apache.catalina.core.StandardContext$NoPluggabilityServletContext.getResource(StandardContext.java:6392) ~[tomcat-embed-core-9.0.14.jar:9.0.14]
	at org.zkoss.web.util.resource.ServletLabelLocator.locate0(ServletLabelLocator.java:94) ~[zweb-8.6.0.jar:8.6.0]
	at org.zkoss.web.util.resource.ServletLabelLocator.locate(ServletLabelLocator.java:77) ~[zweb-8.6.0.jar:8.6.0]
	at org.zkoss.util.resource.impl.LabelLoaderImpl.loadLabels(LabelLoaderImpl.java:272) ~[zcommon-8.6.0.jar:8.6.0]
	at org.zkoss.util.resource.impl.LabelLoaderImpl.getLabel(LabelLoaderImpl.java:130) ~[zcommon-8.6.0.jar:8.6.0]
	at org.zkoss.util.resource.impl.LabelLoaderImpl.getLabel(LabelLoaderImpl.java:121) ~[zcommon-8.6.0.jar:8.6.0]


```

**Comment by cor3000** [comment]
During my tests I/we ever encountered this kind of error. 
Can you provide the environment details (versions, IDE, plugins) and a minimal runnable project reproducing the problem?

**Comment by sesong11** [comment]
Springboot 2.1.3.RELEASE
ZK CE 8.6.0 
zkspringboot 1.0.4
OpenJDK 11
IntelliJ IDEA 2018.3.2
Maven 3.6.0
Project running find without Spring boot Devtools, when I add Devtools dependency to project and change the code it auto reload. Everything work find except Labels. I will create a run able project for you later.

**Comment by sesong11** [comment]
Here is the code that reproduce exception
You can use any IDE (IntelliJ or Eclipse) which enable auto build, when you change any code on MinimalWarApplication project will auto reload and throw exception as describe above.

https://github.com/sesong11/zkspringboot/tree/master/zkspringboot-demos/zkspringboot-minimal-war

**Comment by cor3000** [comment]
I think it has to do with the fact how ZK uses static methods and fields:
`	at org.zkoss.util.resource.Labels.getSegmentedLabels(Labels.java:124)`

The Labels class is caching a LabelLoader(Impl) which internally caches the ServletLabelLoader which caches the ServletContext. When Spring boot restarts the the spring context it seems to also create a new ServletContext, but ZK still caches the old one (which is already stopped). -> hence the error message "The resources may not be accessed if they are not currently started"

Nothing we can do about it in zk-spring-boot directly as it is an internal implementation in the ZK framework.

You might try implementing a custom LabelLoader or LabelLocator that doesn't cache the servletcontext. 

Otherwise it seems you can't use this feature, to restart the server automatically. However in many cases you don't need to restart the server at all when developing ZK pages, labels, and js or css resources. Just look into ZK's devcofig example which disables many internal caches inside ZK to reduce necessary restarts.

https://github.com/zkoss/zkspringboot/blob/master/zkspringboot-demos/zkspringboot-demo-jar/src/main/java/org/zkoss/zkspringboot/demo/DevelopmentConfig.java

**Comment by sesong11** [comment]
Is it possible to disable this cache or clear it when system restart?

**Comment by cor3000** [comment]
good question:
since it's a java static initializer there's no config option for that ... however I'll try with WebappInit listener and reflection to clear out this field, or refill it accordingly ... however this might not be the only problem area (ZK was created way before spring boot, so it assumes to run in a single servlet context)

**Comment by cor3000** [comment]
good news I had some luck doing this:

```
public class MinimalWarApplication extends SpringBootServletInitializer {

	@Override
	protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
		resetLabelLoader();
		return application.sources(MinimalWarApplication.class);
	}

	public static void main(String[] args) {
		resetLabelLoader();
		SpringApplication.run(MinimalWarApplication.class);
	}

	private static void resetLabelLoader() {
		try {
			final Field field = Labels.class.getDeclaredField("_loader");
			field.setAccessible(true);
			field.set(null, new LabelLoaderImpl());
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
```

This seems to work when running the application either via maven spring-boot:run or the main method directly (as a java application)

**Comment by sesong11** [comment]
> good news, I had some luck doing the following:
> 
> ```
> public class MinimalWarApplication extends SpringBootServletInitializer {
> 
> 	@Override
> 	protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
> 		resetLabelLoader();
> 		return application.sources(MinimalWarApplication.class);
> 	}
> 
> 	public static void main(String[] args) {
> 		resetLabelLoader();
> 		SpringApplication.run(MinimalWarApplication.class);
> 	}
> 
> 	private static void resetLabelLoader() {
> 		try {
> 			final Field field = Labels.class.getDeclaredField("_loader");
> 			field.setAccessible(true);
> 			field.set(null, new LabelLoaderImpl());
> 		} catch (Exception e) {
> 			e.printStackTrace();
> 		}
> 	}
> ```
> This seems to work when running the application either via `maven spring-boot:run` or the main() method directly (as a java application)

**Comment by sesong11** [comment]
Awesome, It work with Eclipse and IntelliJ auto build too
