### ISSUE TITLE
Is this for ZK EE?

### ISSUE THREAD

**Issue by sesong11** [zkoss/zkspringboot#4]
You're using ZK 8.5.2.1, it's EE version. Is this going to release for ZK CE too?

**Comment by cor3000** [comment]
you can also use version 8.5.0 CE

**Comment by sesong11** [comment]
@cor3000 when I try to use 8.5.0 CE my zats test run with errors

    
java.lang.IllegalArgumentException: couldn't initialize contextConfigLocation
	at org.zkoss.zkspringboot.zats.ZatsSpringBootContextLoaderListener$ZatsSpringBootServletInitializer.configure(ZatsSpringBootContextLoaderListener.java:52) ~[zkspringboot-autoconfig-1.0.3.jar:na]
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:122) ~[spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.zkoss.zkspringboot.zats.ZatsSpringBootContextLoaderListener$ZatsSpringBootServletInitializer.onStartup(ZatsSpringBootContextLoaderListener.java:42) ~[zkspringboot-autoconfig-1.0.3.jar:na]
	at org.zkoss.zkspringboot.zats.ZatsSpringBootContextLoaderListener.contextInitialized(ZatsSpringBootContextLoaderListener.java:23) ~[zkspringboot-autoconfig-1.0.3.jar:na]
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:952) ~[jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:558) ~[jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:917) ~[jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:370) ~[jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497) ~[jetty-webapp-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459) ~[jetty-webapp-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:847) ~[jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287) ~[jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545) ~[jetty-webapp-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.Server.start(Server.java:416) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
    ....

**Comment by sesong11** [comment]
It was my bad, I did not set contextConfigLocation on  test web.xml file to my Spring boot Application. Thanks for awesome framework

**Comment by cor3000** [comment]
just to be precise ...
for your spring boot war file you don't need to set the contextConfigLocation in [src/**main**/webapp/WEB-INF/web.xml](https://github.com/zkoss/zkspringboot/blob/master/zkspringboot-demos/zkspringboot-minimal-war/src/main/webapp/WEB-INF/web.xml)

but for ZATS you need it in [src/test/webapp/WEB-INF/web.xml](https://github.com/zkoss/zkspringboot/blob/master/zkspringboot-demos/zkspringboot-minimal-war/src/test/webapp/WEB-INF/web.xml) - because ZATS starts it's own internal jetty which is unaware of spring boot
