### ISSUE TITLE
Include doesn't work

### ISSUE THREAD

**Issue by arcangelsalazar** [zkoss/zkspringboot#47]
Including a file using 
```
<zk>
    <div>
        this is another page
    </div>
    <include src="~./main.zul"/>
</zk>
```
or
```
<zk>
    <div>
        this is another page
    </div>
    <include src="/main"/>
</zk>

```
it's not working in any way. you always get:

Page not found: ~./main.zul
	at org.zkoss.zk.ui.http.ExecutionImpl.getPageDefinition(ExecutionImpl.java:396) ~[zk-10.0.0-jakarta.jar:10.0.0-migrated-1.0.0]
	at org.zkoss.zul.Include.afterCompose(Include.java:509) ~[zul-10.0.0-jakarta.jar:10.0.0-migrated-1.0.0]
	at org.zkoss.zk.ui.impl.UiEngineImpl.execCreateChild0(UiEngineImpl.java:942) ~[zk-10.0.0-jakarta.jar:10.0.0-migrated-1.0.0]
	at org.zkoss.zk.ui.impl.UiEngineImpl.execCreateChild(UiEngineImpl.java:891) ~[zk-10.0.0-jakarta.jar:10.0.0-migrated-1.0.0]
	at org.zkoss.zk.ui.impl.UiEngineImpl.execCreate0(UiEngineImpl.java:778) ~[zk-10.0.0-jakarta.jar:10.0.0-migrated-1.0.0]
	at org.zkoss.zk.ui.impl.UiEngineImpl.execCreateChild(UiEngineImpl.java:838) ~[zk-10.0.0-jakarta.jar:10.0.0-migrated-1.0.0]
	at org.zkoss.zk.ui.impl.UiEngineImpl.execCreate0(UiEngineImpl.java:796) ~[zk-10.0.0-jakarta.jar:10.0.0-migrated-1.0.0]
	at org.zkoss.zk.ui.impl.UiEngineImpl.execCreate(UiEngineImpl.java:742) ~[zk-10.0.0-jakarta.jar:10.0.0-migrated-1.0.0]
	at org.zkoss.zk.ui.impl.UiEngineImpl.execNewPage0(UiEngineImpl.java:465) ~[zk-10.0.0-jakarta.jar:10.0.0-migrated-1.0.0]
	at org.zkoss.zk.ui.impl.UiEngineImpl.execNewPage(UiEngineImpl.java:373) ~[zk-10.0.0-jakarta.jar:10.0.0-migrated-1.0.0]
	at org.zkoss.zk.ui.http.ZumlExtendlet.process(ZumlExtendlet.java:144) ~[zk-10.0.0-jakarta.jar:10.0.0-migrated-1.0.0]
	at org.zkoss.zk.ui.http.ZumlExtendlet.service(ZumlExtendlet.java:115) ~[zk-10.0.0-jakarta.jar:10.0.0-migrated-1.0.0]
	at org.zkoss.web.util.resource.ClassWebResource.web0(ClassWebResource.java:599) ~[zweb-10.0.0-jakarta.jar:10.0.0-migrated-1.0.0]
	at org.zkoss.web.util.resource.ClassWebResource.web(ClassWebResource.java:586) ~[zweb-10.0.0-jakarta.jar:10.0.0-migrated-1.0.0]
	at org.zkoss.web.util.resource.ClassWebResource.service(ClassWebResource.java:295) ~[zweb-10.0.0-jakarta.jar:10.0.0-migrated-1.0.0]
	at org.zkoss.zk.au.http.DHtmlResourceServlet.doGet0(DHtmlResourceServlet.java:125) ~[zk-10.0.0-jakarta.jar:10.0.0-migrated-1.0.0]
	at org.zkoss.zk.au.http.DHtmlUpdateServlet.doGet(DHtmlUpdateServlet.java:343) ~[zk-10.0.0-jakarta.jar:10.0.0-migrated-1.0.0]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564) ~[tomcat-embed-core-10.1.19.jar:6.0]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.19.jar:6.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[tomcat-embed-core-10.1.19.jar:10.1.19]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.19.jar:10.1.19]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-10.1.19.jar:10.1.19]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.19.jar:10.1.19]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.19.jar:10.1.19]
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108) ~[spring-web-6.1.4.jar:6.1.4]
	at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231) ~[spring-security-web-6.2.2.jar:6.2.2]
	at org.springframework.security.web.ObservationFilterChainDecorator$FilterObservation$SimpleFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:479) ~[spring-security-web-6.2.2.jar:6.2.2]
	at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:340) ~[spring-security-web-6.2.2.jar:6.2.2]
	at org.springframework.security.web.ObservationFilterChainDecorator.lambda$wrapSecured$0(ObservationFilterChainDecorator.java:82) ~[spring-security-web-6.2.2.jar:6.2.2]
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:128) ~[spring-security-web-6.2.2.jar:6.2.2]
	at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:100) ~[spring-security-web-6.2.2.jar:6.2.2]

The template system is also not working. Looks like the system is unable to resolve the files in the filesystem.

gradle dependencies:

implementation("org.springframework.boot:spring-boot-starter")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("org.springframework.boot:spring-boot-starter-security")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.zkoss.zkspringboot:zkspringboot-starter:3.2.3")
    implementation("org.zkoss.zk:zk:10.0.0-jakarta") // ZK dependency
    implementation ("org.zkoss.zk:zkbind:10.0.0-jakarta")
    implementation ("org.zkoss.zk:zul:10.0.0-jakarta")
    implementation ("org.zkoss.zk:zkplus:10.0.0-jakarta")
    implementation ("org.zkoss.zk:zhtml:10.0.0-jakarta")
    implementation("org.postgresql:postgresql")

**Comment by cor3000** [comment]
to me things are working as expected:

I adjusted the example project `zkspringboot-minimal-jar` to demonstrate 

- `<include>`
- `<apply>`
- `<forEach>`

[issue47.zip](https://github.com/user-attachments/files/16478324/issue47.zip)

you can download, unzil and run the example via `gradle bootRun`

Since you didn't provide your folder structure I just followed the example structure where the zul files are located under

`src/main/resources/web/zul/`

the corresponding include src is then:

	<include src="~./zul/main.zul"/>

the prefix ~./ expands to the `web` package under `src/main/resources`, any path after that are up to you to decide here I chose `zul`, you can even put zul files directly under the `web` folder. Then the include src would be `~./main.zul` as in your example.

about the templating mechanism not working:

you need to add the zkmax and zuti dependencies in order to use zk's shadow elements such as `<apply>,<if>,<forEach>`, that's why I used the `-Eval` versions in the example provided.

**Comment by arcangelsalazar** [comment]
Just checked, the trick was the "~./". Please, add to the readme the way you need to call the .zul files.

**Comment by cor3000** [comment]
This is not a specific zkspringboot feature. Just a limitation of spring boot packaging/running in jar mode.

The differences are documented here https://www.zkoss.org/wiki/ZK_Installation_Guide/Quick_Start/Create_and_Run_Your_First_ZK_Application_with_Spring_Boot#Application_structure

I guess this document could be linked.
