### ISSUE TITLE
ZK WebManager already exists. Could not initialize via Spring Boot configuration.

### ISSUE THREAD

**Issue by sesong11** [zkoss/zkspringboot#5]
I create a spring boot application from start.spring.io, and add zkspringboot-starter 1.0.3 to my application, and make it as war package. when I run with mvn spring-boot:run it work. But when I deploy to tomcat 8.5 I receive an error on start tomcat.

    java.lang.IllegalStateException: ZK WebManager already exists. Could not initialize via Spring Boot configuration.
	at org.zkoss.zkspringboot.ZkAutoConfiguration$1.contextInitialized(ZkAutoConfiguration.java:90)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4743)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:986)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:507)
	at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1651)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)

**Comment by sesong11** [comment]
I has found the solution, 
1. create and web.xml file
2. set zk.springboot-packaging=war

then fixed the issue
