### ISSUE TITLE
connection exception: closed when run multiple zats test

### ISSUE THREAD

**Issue by sesong11** [zkoss/zkspringboot#6]
I write two zats test, each of them has AutoEvironment, when I run one by one they success. but when I run them together, the second zats test not success, with error.

    Caused by: org.hsqldb.HsqlException: connection exception: closed
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)

my source code: https://github.com/sesong11/zboot

**Comment by sesong11** [comment]
I found solution by add these to application.properties
    spring.jpa.generate-ddl=true
    spring.datasource.generate-unique-name=true
    spring.jmx.enabled=false
